## 异步线程配置 自定义使用参数
async:
  executor:
    thread:
      # 配置核心线程数 默认8个 核数*2+2
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 10
      # 配置队列大小
      queue_capacity: 99999
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-service-